//! Complete native paired observations. Python model history stays declared in saved artifacts.
use super::artifact::{digest, outcome};
use super::{
    CapturedCodingInput, CodingCaseObservation, CodingReport, CodingRuntimeIdentity, observe_coding,
};
use anyhow::ensure;
use gw_schema::{
    CODING_PAIR_MAX_BYTES, CodingGeneratedRepresentation, CodingModelSide, CodingPairRequest,
    CodingPopulation, CodingTaskDocument, ExecutionOutcome, coding_digest,
};
use gw_storage::CapturedCodingPopulation;
use serde::{Deserialize, Serialize};
use tokio_util::sync::CancellationToken;

/// One exact side/member result, retaining uncertainty and complete native case observations.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CodingPairedOutcome {
    /// Exact comparison side.
    pub side: CodingModelSide,
    /// Exact accepted member identity.
    pub member_id: String,
    /// Exact base or base-plus-adapter identity.
    pub model_id: String,
    /// Complete corresponding generation-row identity.
    pub generation_id: String,
    /// Exact body bytes when a completed generation returned, including unsupported bodies.
    pub code_id: Option<String>,
    /// Pass, Fail or Unknown, never a numeric substitute for uncertainty.
    pub outcome: ExecutionOutcome,
    /// Stable boundary reason: native, unsupported representation, generation, cancellation or infrastructure.
    pub reason: String,
    /// Complete redacted native observations when execution actually started and returned.
    pub native: Option<CodingReport>,
}
/// Descriptive whole-population counts; these do not perform statistical promotion.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CodingSideCounts {
    /// Every captured held-out member.
    pub items: u32,
    /// Complete observed native passes.
    pub passed: u32,
    /// Observed format or native failures.
    pub failed: u32,
    /// Unobserved or unsettled items, retained explicitly.
    pub unknown: u32,
}
/// Entire paired result, atomically published by its owning controller only after validation.
/// All historical model/training/execution fields remain declarations after deserialization.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CodingPairedArtifact {
    /// Exactly one.
    pub version: u32,
    /// Integrity over the whole complete report, not a producer signature.
    pub artifact_id: String,
    /// Complete captured redacted population; no protected values or reference modules.
    pub population: CodingPopulation,
    /// Both complete model/generation sides and their source identities.
    pub request: CodingPairRequest,
    /// Exact native local runtime recipe.
    pub runtime: CodingRuntimeIdentity,
    /// Actual native controller source identity.
    pub executor_id: String,
    /// Actual native interpretation and paired arithmetic source identity.
    pub scorer_id: String,
    /// Both ordered sides of every item, including failures and Unknown.
    pub rows: Vec<CodingPairedOutcome>,
    /// Complete base coverage arithmetic.
    pub base: CodingSideCounts,
    /// Complete candidate coverage arithmetic.
    pub candidate: CodingSideCounts,
    /// True only when every item on both sides has an observed non-Unknown outcome.
    pub comparable: bool,
    /// Candidate pass count minus base pass count, absent unless the entire pair is comparable.
    pub passed_difference: Option<i32>,
    /// Always false. This descriptive result never authorizes promotion.
    pub automatic_promotion: bool,
    /// Always declared when persisted; only live controller ownership establishes freshness.
    pub historical_training: String,
    /// Always declared when persisted, even if generated by a fresh local controller.
    pub historical_generation: String,
    /// Always declared when persisted; explicit replay establishes a new native observation.
    pub historical_execution: String,
    /// Previous saved report checked by this fresh execution, when replay was requested.
    pub replayed_declaration_id: Option<String>,
}
/// Fresh non-deserializable native observations. It does not authenticate Python model history.
pub struct ObservedCodingPair {
    artifact: CodingPairedArtifact,
}
impl ObservedCodingPair {
    /// Consume fresh native observations into an inspectable saved declaration.
    #[must_use]
    pub fn into_artifact(self) -> CodingPairedArtifact {
        self.artifact
    }
}
fn executor_id() -> String {
    coding_digest(
        "ghostwriter.paired-coding-executor.v1",
        concat!(
            include_str!("mod.rs"),
            include_str!("container.rs"),
            include_str!("process.rs"),
            include_str!("runtime.rs"),
            include_str!("artifact.rs"),
            include_str!("wrapper.py"),
            include_str!("../commands/coding_pair.rs"),
            include_str!("../../../gw-storage/src/coding_population.rs")
        )
        .as_bytes(),
    )
}
fn scorer_id() -> String {
    coding_digest(
        "ghostwriter.paired-coding-scorer.v1",
        concat!(
            include_str!("paired.rs"),
            include_str!("consume.rs"),
            include_str!("../../../gw-schema/src/coding_generation_validation.rs"),
            include_str!("../../../gw-schema/src/coding_population.rs"),
            include_str!("../../../gw-judge/src/verifier/mod.rs"),
            include_str!("../../../gw-judge/src/verifier/rail.rs"),
            include_str!("../../../gw-judge/src/verifier/evidence.rs"),
            include_str!("../../../gw-judge/src/interpretation.rs")
        )
        .as_bytes(),
    )
}
fn counts(rows: &[CodingPairedOutcome], side: CodingModelSide) -> CodingSideCounts {
    let mut result = CodingSideCounts::default();
    for row in rows.iter().filter(|row| row.side == side) {
        result.items += 1;
        match row.outcome {
            ExecutionOutcome::Passed => result.passed += 1,
            ExecutionOutcome::Failed => result.failed += 1,
            ExecutionOutcome::Unknown => result.unknown += 1,
        }
    }
    result
}
impl CodingPairedArtifact {
    fn identity(&self) -> String {
        let mut copy = self.clone();
        copy.artifact_id.clear();
        digest("ghostwriter.paired-coding-artifact.v1", &copy)
    }
    fn seal(&mut self) {
        self.artifact_id = self.identity();
    }
    /// Strict bounded saved inspection, without any execution or model capability.
    ///
    /// # Errors
    /// Rejects unknown/missing fields, incomplete or swapped coverage, forged flags or arithmetic.
    pub fn from_json(bytes: &[u8]) -> anyhow::Result<Self> {
        ensure!(
            bytes.len() <= CODING_PAIR_MAX_BYTES,
            "paired artifact exceeds bound"
        );
        let value = gw_schema::strict_coding_json(bytes).map_err(anyhow::Error::msg)?;
        let artifact: Self = serde_json::from_value(value.clone())?;
        ensure!(
            serde_json::to_value(&artifact)? == value,
            "paired artifact has unknown or omitted fields"
        );
        artifact.validate()?;
        Ok(artifact)
    }
    /// Verify complete captured bindings and recompute case interpretation and descriptive counts.
    ///
    /// # Errors
    /// Rejects contradictory or stale saved declarations. Consistency never authenticates history.
    pub fn validate(&self) -> anyhow::Result<()> {
        self.request
            .validate(&self.population)
            .map_err(anyhow::Error::msg)?;
        ensure!(
            self.version == 1
                && self.artifact_id == self.identity()
                && self.runtime == CodingRuntimeIdentity::expected()
                && self.executor_id == executor_id()
                && self.scorer_id == scorer_id()
                && self.rows.len() == self.request.rows.len()
                && !self.automatic_promotion
                && self.historical_training == "declared"
                && self.historical_generation == "declared"
                && self.historical_execution == "declared",
            "paired artifact identity, runtime or saved authority claim differs"
        );
        for ((row, answer), member) in self
            .rows
            .iter()
            .zip(&self.request.rows)
            .zip(self.population.members.iter().flat_map(|m| [m, m]))
        {
            let body = answer
                .generation
                .as_ref()
                .map(|g| g.output.body_text.as_str());
            ensure!(
                row.side == answer.side
                    && row.member_id == member.member_id
                    && row.model_id == answer.model_id
                    && row.generation_id
                        == digest("ghostwriter.coding-generated-answer.v1", answer)
                    && row.code_id
                        == body
                            .map(|s| coding_digest("ghostwriter.coding-module.v1", s.as_bytes())),
                "paired outcome side, member, model or exact module was substituted"
            );
            let representation = answer.generation.as_ref().map(|g| g.output.representation);
            if let Some(native) = &row.native {
                ensure!(
                    representation == Some(CodingGeneratedRepresentation::Module)
                        && row.reason == "native"
                        && native.run_id.len() == 32
                        && native.run_id.bytes().all(|b| b.is_ascii_hexdigit())
                        && native
                            .cases
                            .iter()
                            .map(|c| &c.case_id)
                            .eq(member.suite.case_ids.iter()),
                    "native paired execution lacks exact module or full case coverage"
                );
                for case in &native.cases {
                    case.validate()?;
                }
                ensure!(
                    native.outcome == outcome(&native.cases)
                        && row.outcome == native.outcome
                        && native.native_verification
                            == super::consume::interpret_public(
                                member,
                                body.expect("module"),
                                &native.run_id,
                                &native.cases
                            ),
                    "paired native outcome or verification was forged"
                );
            } else {
                let expected = match representation {
                    Some(CodingGeneratedRepresentation::Unsupported) => {
                        (ExecutionOutcome::Failed, "unsupported_representation")
                    }
                    None | Some(CodingGeneratedRepresentation::Unknown) => {
                        (ExecutionOutcome::Unknown, "generation_unknown")
                    }
                    Some(CodingGeneratedRepresentation::Module) => {
                        ensure!(
                            ["cancelled", "infrastructure"].contains(&row.reason.as_str()),
                            "unexecuted module requires cancellation or infrastructure uncertainty"
                        );
                        (ExecutionOutcome::Unknown, row.reason.as_str())
                    }
                };
                ensure!(
                    row.outcome == expected.0
                        && row.reason == expected.1
                        && [
                            "unsupported_representation",
                            "generation_unknown",
                            "cancelled",
                            "infrastructure"
                        ]
                        .contains(&row.reason.as_str()),
                    "unexecuted paired item cannot declare native success"
                );
            }
        }
        let base = counts(&self.rows, CodingModelSide::Base);
        let candidate = counts(&self.rows, CodingModelSide::Candidate);
        let complete = base.unknown == 0 && candidate.unknown == 0;
        ensure!(
            self.base == base
                && self.candidate == candidate
                && self.comparable == complete
                && self.passed_difference
                    == complete.then_some(candidate.passed as i32 - base.passed as i32),
            "paired arithmetic omitted uncertainty or incomplete coverage"
        );
        if let Some(id) = &self.replayed_declaration_id {
            ensure!(
                id.len() == 64 && id.bytes().all(|b| b.is_ascii_hexdigit()),
                "invalid paired predecessor identity"
            );
        }
        Ok(())
    }
}

/// Execute both complete answer sets against one opaque native held-out population capture.
/// Any saved generation fields remain declared; only native coding execution is observed here.
///
/// # Errors
/// Rejects incomplete, foreign or swapped requests before Docker. Runtime uncertainty is retained.
pub async fn observe_pair(
    population: CapturedCodingPopulation,
    request: CodingPairRequest,
    cancel: CancellationToken,
) -> anyhow::Result<ObservedCodingPair> {
    request
        .validate(population.public())
        .map_err(anyhow::Error::msg)?;
    let document = CodingTaskDocument {
        version: 1,
        tasks: population.private_tasks().to_vec(),
    };
    let mut rows = Vec::with_capacity(request.rows.len());
    for (answer, task) in request
        .rows
        .iter()
        .zip(document.tasks.iter().flat_map(|task| [task, task]))
    {
        let generation = answer.generation.as_ref();
        let mut row = CodingPairedOutcome {
            side: answer.side,
            member_id: answer.member_id.clone(),
            model_id: answer.model_id.clone(),
            generation_id: digest("ghostwriter.coding-generated-answer.v1", answer),
            code_id: generation.map(|g| {
                coding_digest(
                    "ghostwriter.coding-module.v1",
                    g.output.body_text.as_bytes(),
                )
            }),
            outcome: ExecutionOutcome::Unknown,
            reason: "generation_unknown".into(),
            native: None,
        };
        if let Some(generation) = generation {
            match generation.output.representation {
                CodingGeneratedRepresentation::Unsupported => {
                    row.outcome = ExecutionOutcome::Failed;
                    row.reason = "unsupported_representation".into();
                }
                CodingGeneratedRepresentation::Unknown => {}
                CodingGeneratedRepresentation::Module => {
                    if cancel.is_cancelled() {
                        row.reason = "cancelled".into();
                    } else {
                        let input = CapturedCodingInput::new(
                            &document,
                            &task.task_id,
                            generation.output.body_text.clone(),
                        )?;
                        match observe_coding(input, cancel.clone()).await {
                            Ok(observed) => {
                                let artifact = observed.consume();
                                row.outcome = artifact.report.outcome;
                                row.reason = "native".into();
                                row.native = Some(artifact.report);
                            }
                            Err(_) => {
                                row.reason = "infrastructure".into();
                            }
                        }
                    }
                }
            }
        }
        rows.push(row);
    }
    let base = counts(&rows, CodingModelSide::Base);
    let candidate = counts(&rows, CodingModelSide::Candidate);
    let comparable = base.unknown == 0 && candidate.unknown == 0;
    let mut artifact = CodingPairedArtifact {
        version: 1,
        artifact_id: String::new(),
        population: population.public().clone(),
        request,
        runtime: CodingRuntimeIdentity::expected(),
        executor_id: executor_id(),
        scorer_id: scorer_id(),
        rows,
        passed_difference: comparable.then_some(candidate.passed as i32 - base.passed as i32),
        base,
        candidate,
        comparable,
        automatic_promotion: false,
        historical_training: "declared".into(),
        historical_generation: "declared".into(),
        historical_execution: "declared".into(),
        replayed_declaration_id: None,
    };
    artifact.seal();
    artifact.validate()?;
    Ok(ObservedCodingPair { artifact })
}

/// Re-execute saved modules against the same complete registered population and compare outcomes.
/// No model is loaded, and saved generation/training history stays declared.
///
/// # Errors
/// Rejects changed membership or any disagreement with the saved complete coding observations.
pub async fn replay_pair(
    population: CapturedCodingPopulation,
    saved: CodingPairedArtifact,
    cancel: CancellationToken,
) -> anyhow::Result<ObservedCodingPair> {
    saved.validate()?;
    ensure!(
        population.public() == &saved.population,
        "saved population differs from current accepted capture"
    );
    let mut fresh = observe_pair(population, saved.request.clone(), cancel).await?;
    for (before, after) in saved.rows.iter().zip(&fresh.artifact.rows) {
        ensure!(
            before.outcome == after.outcome && before.reason == after.reason,
            "fresh paired coding outcome differs from declaration"
        );
        match (&before.native, &after.native) {
            (None, None) => {}
            (Some(a), Some(b)) => ensure!(
                a.native_verification == b.native_verification
                    && digest(
                        "ghostwriter.coding-stable-report.v1",
                        &a.cases
                            .iter()
                            .map(CodingCaseObservation::stable)
                            .collect::<Vec<_>>()
                    ) == digest(
                        "ghostwriter.coding-stable-report.v1",
                        &b.cases
                            .iter()
                            .map(CodingCaseObservation::stable)
                            .collect::<Vec<_>>()
                    ),
                "fresh paired case observations differ from declaration"
            ),
            _ => anyhow::bail!("fresh paired execution coverage differs from declaration"),
        }
    }
    fresh.artifact.replayed_declaration_id = Some(saved.artifact_id);
    fresh.artifact.seal();
    fresh.artifact.validate()?;
    Ok(fresh)
}
